name: Windows Server 2019

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v2
    - name: rawr
      run: |
        py -m pip install undetected-chromedriver
        py bot2.py
